### ISSUE TITLE
Compile on Raspberry Pi / ARM

### ISSUE THREAD

**Issue by 0rphu** [jprjr/lua-music-visualizer#1]
Hello,
I was trying to compile this on Raspberry Pi 3B, but sice it uses nasm to compile mat.s, it can't be linked. Any idea how to make this run on arm?

**Comment by jprjr** [comment]
I've been meaning to remove that for some time. A while ago I ported this to Windows XP w/ Visual Studio 2005, (which actually helped me find a good number of bugs with mis-matched variable sizes), and that doesn't have the `round` function. So I wrote that, but it actually makes things way less portable.

I'll just remove it, it was only ever really used on that platform.

**Comment by jprjr** [comment]
There you go - still not sure how performance will be, but it should compile!
